import { TComment } from "../../Components/Comments";
import { TTopic } from "../../Components/Topics";

export const testTopics: TTopic[] = [
    {
        id: 0,
        title: "mechanical organizer monitored classic ea",
        message: "heard functions russia vb assigned",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "2017-04-01T15:20:04.685Z",
        messagesCount: 10464,
        author: "username651651",
    },
    {
        id: 1,
        title: "physiology journalist productive picture needed",
        message: "cooperation blood labor investigate mono",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1996-12-04T20:19:10.574Z",
        messagesCount: 44418,
        author: "username651651",
    },
    {
        id: 2,
        title: "isaac inputs super provisions coming",
        message: "framing knowledge bbs transcription frequencies",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "2004-06-16T20:51:44.957Z",
        messagesCount: 62195,
        author: "username651651",
    },
    {
        id: 3,
        title: "eat throat blues i timely",
        message: "parcel f dakota henry suit",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1984-08-24T11:52:09.937Z",
        messagesCount: 14397,
        author: "username651651",
    },
    {
        id: 4,
        title: "workplace honolulu drill russia consistently",
        message: "individuals procurement ef snowboard step",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "2016-05-18T19:12:42.362Z",
        messagesCount: 5102,
        author: "username651651",
    },
    {
        id: 5,
        title: "wound beastality workout pens reducing",
        message: "anxiety quality biodiversity dj commodity",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "2020-10-29T10:24:46.992Z",
        messagesCount: 93517,
        author: "username651651",
    },
    {
        id: 6,
        title: "reason money skirt platinum racial",
        message: "rounds creature jackson pest engage",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1976-04-27T10:20:41.993Z",
        messagesCount: 69627,
        author: "username651651",
    },
    {
        id: 7,
        title: "jc deliver invitation before attributes",
        message: "convention targeted participating guitars angola",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1979-10-23T15:04:21.947Z",
        messagesCount: 9904,
        author: "username651651",
    },
    {
        id: 8,
        title: "christmas vietnam headers corn can",
        message: "enhancements unfortunately colors because penalties",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1999-09-23T05:28:15.654Z",
        messagesCount: 76963,
        author: "username651651",
    },
    {
        id: 9,
        title: "motor covers crop violin naturals",
        message: "aud family tue option question",
        createDate: "2017-04-01T15:20:04.685Z",
        lastMessageDate: "1984-05-30T21:44:17.779Z",
        messagesCount: 39586,
        author: "username651651",
    },
];
export const testComments: TComment[] = [
    {
        author: "Christensen Lynch",
        date: "Wed Sep 09 1970 18:49:41 GMT+0300 (Москва, стандартное время)",
        text: "Incididunt excepteur ex nulla magna adipisicing ipsum sunt eiusmod veniam nisi elit commodo aute. Commodo ea voluptate esse consequat.",
    },
    {
        author: "Francesca Gill",
        date: "Tue Jan 31 2017 03:51:55 GMT+0300 (Москва, стандартное время)",
        text: "Veniam laboris quis irure duis eu minim et eu dolor magna esse fugiat laborum. Laboris qui eu dolor labore minim eiusmod officia deserunt.",
    },
    {
        author: "Sharon Peters",
        date: "Mon Jun 19 1978 02:33:16 GMT+0300 (Москва, стандартное время)",
        text: "Sunt ad amet cillum eu enim ex quis sunt qui laborum non ad sit. Cupidatat officia qui nisi laboris irure voluptate exercitation duis.",
    },
    {
        author: "June Anderson",
        date: "Tue Apr 19 1988 10:40:21 GMT+0400 (Москва, летнее время)",
        text: "Velit occaecat adipisicing sunt dolore id non Lorem aute. Lorem sint ad voluptate ea ullamco reprehenderit nisi veniam id proident ut nisi.",
    },
    {
        author: "Dixie Wade",
        date: "Thu Apr 05 1973 12:37:19 GMT+0300 (Москва, стандартное время)",
        text: "Adipisicing labore duis minim aliquip. Cupidatat duis cupidatat voluptate cupidatat id quis.",
    },
    {
        author: "Rodgers Everett",
        date: "Mon Mar 05 2007 06:33:20 GMT+0300 (Москва, стандартное время)",
        text: "Deserunt qui dolor sit officia elit reprehenderit in eu nisi quis magna ipsum. Deserunt adipisicing aliquip mollit cillum irure.",
    },
    {
        author: "Kim Glass",
        date: "Wed Apr 22 2020 08:23:46 GMT+0300 (Москва, стандартное время)",
        text: "Incididunt veniam laboris esse dolore cillum exercitation enim in do culpa non minim. Excepteur et cupidatat nostrud Lorem ea tempor.",
    },
    {
        author: "Price Gonzales",
        date: "Thu Oct 10 1996 11:13:20 GMT+0400 (Москва, летнее время)",
        text: "Ut elit anim consectetur sint magna do dolor. Cupidatat consectetur ullamco minim magna laboris amet ullamco reprehenderit ad nulla minim magna quis eiusmod.",
    },
    {
        author: "Alexandria Bates",
        date: "Wed Jun 15 1988 22:36:39 GMT+0400 (Москва, летнее время)",
        text: "Pariatur sunt ipsum adipisicing sint. Ipsum sint reprehenderit laborum incididunt esse non esse nisi eiusmod.",
    },
    {
        author: "Evelyn Fitzgerald",
        date: "Thu Jul 20 2006 19:50:39 GMT+0400 (Москва, летнее время)",
        text: "Non in duis exercitation anim fugiat excepteur excepteur qui anim adipisicing ea est qui proident. Proident ipsum labore quis nisi Lorem Lorem aliqua id occaecat labore nostrud.",
    },
    {
        author: "Hester Silva",
        date: "Fri Feb 21 2014 01:07:53 GMT+0400 (Москва, стандартное время)",
        text: "Excepteur irure eu pariatur velit sit ullamco magna cupidatat aliquip non exercitation sunt. Aute consectetur aliqua nulla deserunt cupidatat laborum officia proident veniam sint est.",
    },
    {
        author: "Stout Chase",
        date: "Wed Sep 22 2010 12:57:21 GMT+0400 (Москва, летнее время)",
        text: "Occaecat veniam aliqua ex elit veniam ad esse occaecat cupidatat. Ipsum occaecat quis minim occaecat elit eu Lorem labore excepteur officia fugiat aliquip tempor.",
    },
    {
        author: "Cote Gonzalez",
        date: "Sat Sep 13 2008 02:18:37 GMT+0400 (Москва, летнее время)",
        text: "Laborum quis ipsum pariatur aute minim officia ullamco ad dolore non mollit. Esse officia cupidatat magna sunt excepteur consequat do Lorem qui qui minim cillum occaecat.",
    },
    {
        author: "Paul Russo",
        date: "Tue Jul 05 2011 03:05:40 GMT+0400 (Москва, стандартное время)",
        text: "Ut aliqua anim aliquip amet enim minim aliqua cillum. Sunt proident exercitation irure consequat dolor duis proident deserunt culpa qui laborum.",
    },
    {
        author: "Carney Frost",
        date: "Mon Apr 16 2012 07:57:04 GMT+0400 (Москва, стандартное время)",
        text: "Nostrud sunt ad deserunt proident adipisicing aliqua anim duis. Officia consectetur incididunt sint ut commodo reprehenderit laborum nulla nulla qui excepteur cillum cupidatat.",
    },
    {
        author: "Haney Chandler",
        date: "Tue Sep 12 1995 21:55:25 GMT+0400 (Москва, летнее время)",
        text: "Esse sint irure Lorem consectetur ea sunt velit mollit quis cillum pariatur velit in sint. Proident nisi ea sunt amet quis aliquip.",
    },
    {
        author: "Mccormick Day",
        date: "Thu Sep 27 2001 12:32:26 GMT+0400 (Москва, летнее время)",
        text: "Officia exercitation laboris anim magna mollit. In culpa cupidatat voluptate et irure ad id mollit non.",
    },
];
